(ert-deftest key-chord-test-key-chord-match ()
  (should (key-chord-match '() '()))
  (should (key-chord-match '(a) '(a)))
  (should (key-chord-match '(a b) '(a b)))
  (should (not (key-chord-match '() '(a))))
  (should (not (key-chord-match '(a) '())))
  (should (not (key-chord-match '(b) '(a b))))
  (should (not (key-chord-match '(a b) '(b)))))

(ert-deftest key-chord-test-traverse-branch ()
  (let ((available-keychord-sequences)
        (keymap-nil '())
        (keymap-a '(48 keymap (117 . symbol)))
        (keymap-b '(11 keymap (12 keymap (13 . symbol))))
        (keymap-c '(1 keymap (2 keymap (3 . symbol1)) (4 keymap (5 . symbol2)))))
    (traverse-branch keymap-nil)
    (should (equal available-keychord-sequences '()))
    (setq available-keychord-sequences nil)
    (traverse-branch keymap-a)
    (should (equal available-keychord-sequences '((symbol 48 117))))
    (setq available-keychord-sequences nil)
    (traverse-branch keymap-b)
    (should (equal available-keychord-sequences '((symbol 11 12 13))))
    (setq available-keychord-sequences nil)
    (traverse-branch keymap-c)
    (should (equal available-keychord-sequences '((symbol1 1 2 3)
                                                  (symbol2 1 4 5))))))
(ert-deftest key-chord-test-remove-matching-key ()
  (should (equal (remove-matching-key '(symbol 1 2) 1) '(symbol 2)))
  (should (equal (remove-matching-key '(symbol 1 2) 5) '()))
  (should (equal (remove-matching-key '(symbol 1 2 3 4) 5) '()))
  (should (equal (remove-matching-key '(symbol 1 2 3 4) 2) '(symbol 1 3 4))))

(ert-deftest key-chord-test-filter-out-empty-list ()
  (let ((available-keychord-sequences))
    (setq available-keychord-sequences '())
    (filter-out-empty-lists)
    (should (equal available-keychord-sequences '()))
    (setq available-keychord-sequences '((1 2 symbol)))
    (filter-out-empty-lists)
    (should (equal available-keychord-sequences '((1 2 symbol))))
    (setq available-keychord-sequences '(()))
    (filter-out-empty-lists)
    (should (equal available-keychord-sequences '()))
    (setq available-keychord-sequences '((1 2 symbol) () (2 2 symbol)))
    (filter-out-empty-lists)
    (should (equal available-keychord-sequences '((1 2 symbol) (2 2 symbol))))))
    
