#!/usr/bin/expect

# debugging
# exp_internal 1

proc wait {} {
    sleep .2
}

spawn emacs -nw -Q -L .. -L test_libs -l key-chord-multiple-acceptance-tests.el

# wait on emacs init, which is showing the scratch buffer
expect "This buffer is for notes"

send "ab"
wait

send "cd,"
wait

send "e"
wait
send "f,"
wait

send "ghijklma,"
wait

send "op"
wait

send "(this should insert something -> q <- ending macro)"
send "e,"
wait

send "(this should insert something -> rst <- ending macro)"
send "e,"
wait

# for some reason doing uv in one send doesn't work, so wait in between
send "uv"
wait
send ""
wait
send "a,"
wait

send ""
